platform :ios, '10.0'

target 'ArReact' do
  pod 'AppCenter/Crashes', '~> 2.5.0'
  pod 'AppCenter/Analytics', '~> 2.5.0'
  pod 'AppCenterReactNativeShared', '~> 2.5.0'
    use_frameworks!
    pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  platform :ios, '9.0'
    pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  end

  # Hack to fix linker error between GVRSDK and React
post_install do |installer|
    system(". ./pod_post_install.sh")
end